version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MEMORY: 2G
      OVERRIDE_SERVER_PROPERTIES: "true"
      ONLINE_MODE: "false"
      SERVER_NAME: "pony minecraft"
      DIFFICULTY: "hard"
      MOTD: "privet! pony mine welcome!"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      PVP: "false"
      MAX_PLAYERS: 5
      ICON: "./server-icon.png"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data:rw
      - ./server-icon.png:/data/server-icon.png:ro
    restart: unless-stopped
volumes:
  mc-paper: {}
